target-version = "py310"

include = [
  "snakehdl/**/*.py",
  "tests/**/*.py",
  "examples/**/*.py",
]

line-length = 150
indent-width = 2

lint.ignore = [
  "E701", # multiple-statements-on-one-line-colon
]

[format]
quote-style = "single"
indent-style = "space"
