name: Tests, Linter, Type Checker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  noncocotbtests:
    name: Non-cocotb Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Run Tests
        run: pytest -k 'not TestVerilogCompiler and not TestVHDLCompiler'
  verilogtests:
    name: VerilogCompiler Tests
    runs-on: ubuntu-latest
    using: verilator/verilator:latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Run Tests
        run: pytest -k TestVerilogCompiler
