name: Tests, Linter, Type Checker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Non-cocotb Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Run Tests
        run: pytest -k 'not TestVerilogCompiler and not TestVHDLCompiler'
  verilogtests:
    name: VerilogCompiler Tests
    runs-on: ubuntu-latest
    container: verilator/verilator:latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Run Tests
        run: pytest -k TestVerilogCompiler
  vhdltests:
    name: VHDLCompiler Tests
    runs-on: ubuntu-latest
    container: ghdl/ghdl:5.0.0-dev-mcode-ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Run Tests
        run: pytest -k TestVHDLCompiler
  linter:
    name: Linter (ruff)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Enviroment
        uses: ./.github/actions/setup-environment
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: python3 -m ruff check
  typechecker:
    name: Typechecker (mypy)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: python3 -m mypy
